name: checkin
on:
  schedule:
    - cron: "45 02 * * *"

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: auto checkin for traffic

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: checkin
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - run: python ./.github/actions/checkin/universal.py

      - name: timestamp
        run: date
